In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv('/content/consumer_insights.csv')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   user_id              5000 non-null   object
 1   persona              4724 non-null   object
 2   trend_affinity       5000 non-null   object
 3   age_group            5000 non-null   object
 4   gender_identity      5000 non-null   object
 5   income_bracket       5000 non-null   object
 6   dietary_restriction  2075 non-null   object
dtypes: object(7)
memory usage: 273.6+ KB

In [ ]:
df.sample(5)

,user_id,persona,trend_affinity,age_group,gender_identity,income_bracket,dietary_restriction
1081,U01082,fitness,low-sugar,25-34,Man,Low,NaN
878,U00879,casual,plant-based,25-34,Man,Medium,NaN
3265,U03266,budget,gut-health,18-24,Woman,Low,Halal
2278,U02279,budget,gut-health,18-24,Man,Low,NaN
473,U00474,fitness,clean-label,18-24,Woman,High,NaN

In [ ]:
df['persona'].value_counts()

persona
fitness    1201
casual     1189
budget     1169
premium    1165
Name: count, dtype: int64

In [ ]:
mask = df['persona'].isna()
df.loc[mask, 'persona'] = np.random.choice(
    ['fitness', 'casual', 'budget', 'premium'],
    size=mask.sum()
)

In [ ]:
df['persona'].value_counts()

persona
fitness    1261
casual     1254
premium    1245
budget     1240
Name: count, dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   user_id              5000 non-null   object
 1   persona              5000 non-null   object
 2   trend_affinity       5000 non-null   object
 3   age_group            5000 non-null   object
 4   gender_identity      5000 non-null   object
 5   income_bracket       5000 non-null   object
 6   dietary_restriction  2075 non-null   object
dtypes: object(7)
memory usage: 273.6+ KB

In [ ]:
con=df

In [ ]:
df=pd.read_csv('/content/geography_occasion.csv')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47581 entries, 0 to 47580
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   order_id   47581 non-null  object
 1   state      47581 non-null  object
 2   city_tier  47581 non-null  object
 3   occasion   47581 non-null  object
dtypes: object(4)
memory usage: 1.5+ MB

In [ ]:
df.sample(5)

        order_id       state city_tier       occasion
44323  ORD046558    Colorado    Tier 1  marathon-prep
38117  ORD039989  Washington    Tier 3      road-trip
46295  ORD048645    New York    Tier 2  marathon-prep
33347  ORD034982    New York    Tier 3    daily snack
3027   ORD003196   Calfornia    Tier 2        festive

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df['state'].value_counts()

state
NY            4898
Illinois      4809
Calfornia     4771
New York      4758
California    4755
Colorado      4748
Washington    4743
Texas         4734
Florida       4688
Georgia       4677
Name: count, dtype: int64

In [ ]:
df['state'] = df['state'].replace({
    'NY': 'New York',
    'Calfornia': 'California'
})

In [ ]:
df['state'].value_counts()

state
New York      9656
California    9526
Illinois      4809
Colorado      4748
Washington    4743
Texas         4734
Florida       4688
Georgia       4677
Name: count, dtype: int64

In [ ]:
geo=df

In [ ]:
df=pd.read_csv('/content/product_metadata (2).csv')

In [ ]:
df.sample(5)

,product_id,category,claims,ingredient_tags,pack_size
84,P085,Protein Bar,kosher,"monk-fruit, oats, pea-protein",4-Pack
142,P143,Protein Bar,"nut-free, kosher, keto-friendly","stevia, oats, almond-flour",Single
138,P139,Healthy Snack,"high-protein, low-sugar, clean-label, jain-fri...",monk-fruit,Single
50,P051,Proten Shake,"vegan, gluten-free, halal","collagen, soy",4-Pack
60,P061,Supplement,"vegan, high-protein, keto-friendly",NaN,4-Pack

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   product_id       150 non-null    object
 1   category         146 non-null    object
 2   claims           150 non-null    object
 3   ingredient_tags  139 non-null    object
 4   pack_size        150 non-null    object
dtypes: object(5)
memory usage: 6.0+ KB

In [ ]:
df['ingredient_tags'].value_counts()

ingredient_tags
monk-fruit                        8
whey                              8
pea-protein                       7
soy                               6
oats                              5
                                 ..
almond-flour, collagen            1
stevia, oats, almond-flour        1
monk-fruit, collagen              1
soy, monk-fruit                   1
oats, monk-fruit, almond-flour    1
Name: count, Length: 80, dtype: int64

In [ ]:
mask1= df['ingredient_tags'].isna()
df.loc[mask1,'ingredient_tags'] = np.random.choice(
    ['monk-fruit','whey','pea-protein','soy','oats'],#andom value from impute from some top frequency
    size=mask1.sum()
)

In [ ]:
df[df['category'].isnull()]

,product_id,category,claims,ingredient_tags,pack_size
54,P055,NaN,"low-sugar, clean-label",monk-fruit,12-Pack
64,P065,NaN,"nut-free, low-sugar","whey, stevia",Single
71,P072,NaN,"gluten-free, low-sugar, halal, kosher","monk-fruit, stevia",4-Pack
77,P078,NaN,"halal, vegan, keto-friendly, clean-label",whey,Single

In [ ]:
df[df['ingredient_tags']=='monk-fruit']

,product_id,category,claims,ingredient_tags,pack_size
2,P003,Proten Shake,jain-friendly,monk-fruit,Single
26,P027,Protein Shake,vegan,monk-fruit,12-Pack
27,P028,Protein Shake,"kosher, plant-based, clean-label, gluten-free",monk-fruit,Single
54,P055,NaN,"low-sugar, clean-label",monk-fruit,12-Pack
62,P063,Protein bar,"low-sugar, keto-friendly, jain-friendly",monk-fruit,12-Pack
69,P070,Protein bar,"high-protein, vegan",monk-fruit,Single
117,P118,Healthy Snack,"kosher, nut-free, clean-label, vegan",monk-fruit,4-Pack
121,P122,Meal Replacement,"halal, high-protein, jain-friendly, keto-friendly",monk-fruit,4-Pack
131,P132,Proten Shake,plant-based,monk-fruit,4-Pack
138,P139,Healthy Snack,"high-protein, low-sugar, clean-label, jain-fri...",monk-fruit,Single

In [ ]:
df['category'].fillna('Proten Shake',inplace=True)

/tmp/ipykernel_19453/832945425.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['category'].fillna('Proten Shake',inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   product_id       150 non-null    object
 1   category         150 non-null    object
 2   claims           150 non-null    object
 3   ingredient_tags  150 non-null    object
 4   pack_size        150 non-null    object
dtypes: object(5)
memory usage: 6.0+ KB

In [ ]:
df.sample(5)

,product_id,category,claims,ingredient_tags,pack_size
60,P061,Supplement,"vegan, high-protein, keto-friendly",whey,4-Pack
38,P039,Protein Shake,"halal, kosher, keto-friendly, nut-free",stevia,4-Pack
148,P149,Protein Bar,clean-label,"oats, stevia, collagen",Single
50,P051,Proten Shake,"vegan, gluten-free, halal","collagen, soy",4-Pack
95,P096,Electrolyte Drink,high-protein,"collagen, monk-fruit, stevia",4-Pack

In [ ]:
product=df

In [ ]:
df=pd.read_csv('/content/transactions.csv')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50150 entries, 0 to 50149
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    50150 non-null  object
 1   user_id     50150 non-null  object
 2   product_id  50150 non-null  object
 3   price       50150 non-null  float64
 4   quantity    50150 non-null  int64
 5   timestamp   50150 non-null  object
 6   channel     50150 non-null  object
dtypes: float64(1), int64(1), object(5)
memory usage: 2.7+ MB

In [ ]:
df.duplicated().sum()

np.int64(150)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 50000 entries, 0 to 50149
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    50000 non-null  object
 1   user_id     50000 non-null  object
 2   product_id  50000 non-null  object
 3   price       50000 non-null  float64
 4   quantity    50000 non-null  int64
 5   timestamp   50000 non-null  object
 6   channel     50000 non-null  object
dtypes: float64(1), int64(1), object(5)
memory usage: 3.1+ MB

In [ ]:
df.sample(5)

,order_id,user_id,product_id,price,quantity,timestamp,channel
24731,ORD041105,U04349,P012,10.59,3,2025-11-12 21:07:04.822715,App
37512,ORD003459,U02553,P147,11.14,2,2025-06-13 23:07:04.822715,Website
32210,ORD048307,U00284,P050,31.84,1,2025-10-28 22:07:04.822715,Website
43074,ORD034688,U03740,P004,37.66,2,2025-10-03 00:07:04.822715,Website
13105,ORD042639,U03053,P016,13.96,3,2025-07-11 23:07:04.822715,Retail

In [ ]:
df['timestamp']=pd.to_datetime(df['timestamp'])
df['date']=df['timestamp'].dt.date
df['time']=df['timestamp'].dt.strftime('%H:%M')

In [ ]:
df.sample(5)

,order_id,user_id,product_id,price,quantity,timestamp,channel,date,time
38865,ORD049833,U02442,P140,11.15,3,2025-05-14 06:07:04.822715,Website,2025-05-14,06:07
31415,ORD004265,U00533,P146,9.16,1,2025-11-18 14:07:04.822715,Gym Kiosk,2025-11-18,14:07
5545,ORD006539,U04987,P137,6.33,2,2025-11-28 13:07:04.822715,Marketplace,2025-11-28,13:07
6453,ORD017207,U01696,P102,27.36,2,2025-10-08 21:07:04.822715,Website,2025-10-08,21:07
27700,ORD002624,U00007,P117,17.76,1,2025-07-01 08:07:04.822715,App,2025-07-01,08:07

In [ ]:
df.drop(columns='timestamp',inplace=True)

In [ ]:
df.sample(5)

,order_id,user_id,product_id,price,quantity,channel,date,time
23289,ORD007978,U02904,P107,8.04,3,App,2025-11-15,18:07
18660,ORD042326,U03782,P124,7.65,2,Marketplace,2025-05-18,06:07
9582,ORD014425,U00082,P115,30.28,1,Retail,2025-10-15,23:07
41406,ORD018378,U04078,P114,15.74,2,Website,2025-06-06,16:07
3556,ORD035514,U04360,P102,18.13,3,Website,2025-05-29,15:07

In [ ]:
df.describe()

              price      quantity
count  50000.000000  50000.000000
mean      56.817239      4.010080
std      407.410673     20.400942
min     -210.160000     -6.000000
25%       10.370000      1.000000
50%       16.800000      2.000000
75%       35.270000      3.000000
max    18641.000000    299.000000

In [ ]:
def neg(x):
  if(x<0):
    return x*(-1)
  else:
    return x
df['price']=df['price'].apply(neg)
df['quantity']=df['quantity'].apply(neg)

In [ ]:
df.describe()

              price      quantity
count  50000.000000  50000.000000
mean      58.154038      4.099600
std      407.222003     20.383141
min        0.000000      1.000000
25%       10.657500      1.000000
50%       17.230000      2.000000
75%       36.870000      3.000000
max    18641.000000    299.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 50000 entries, 0 to 50149
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    50000 non-null  object
 1   user_id     50000 non-null  object
 2   product_id  50000 non-null  object
 3   price       50000 non-null  float64
 4   quantity    50000 non-null  int64
 5   channel     50000 non-null  object
 6   date        50000 non-null  object
 7   time        50000 non-null  object
dtypes: float64(1), int64(1), object(6)
memory usage: 3.4+ MB

In [ ]:
trans=df

In [ ]:
merge_1= pd.merge(trans, product, on='product_id', how='left')

In [ ]:
merge_1.sample(5)

,order_id,user_id,product_id,price,quantity,channel,date,time,category,claims,ingredient_tags,pack_size
28431,ORD032203,U00306,P048,36.48,2,Gym Kiosk,2025-07-13,06:07,Supplement,"nut-free, kosher, low-sugar","pea-protein, almond-flour, whey",4-Pack
14563,ORD015589,U03323,P033,19.53,1,Retail,2025-08-15,23:07,Healthy Snack,"clean-label, keto-friendly, high-protein",whey,Single
2947,ORD048371,U03685,P133,60.40,1,Retail,2025-09-17,16:07,Protein bar,"diabetic-friendly, vegan, clean-label, gluten-...","pea-protein, stevia, collagen",4-Pack
49604,ORD044117,U01634,P128,17.61,1,Retail,2026-03-12,18:07,Meal Replacement,"jain-friendly, low-sugar, diabetic-friendly",oats,Single
11430,ORD047623,U02597,P053,13.65,1,Retail,2025-09-18,07:07,Healthy Snack,vegan,stevia,Single

In [ ]:
merge_2= pd.merge(merge_1, geo, on='order_id', how='left')

In [ ]:
merge_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         50000 non-null  object
 1   user_id          50000 non-null  object
 2   product_id       50000 non-null  object
 3   price            50000 non-null  float64
 4   quantity         50000 non-null  int64
 5   channel          50000 non-null  object
 6   date             50000 non-null  object
 7   time             50000 non-null  object
 8   category         50000 non-null  object
 9   claims           50000 non-null  object
 10  ingredient_tags  50000 non-null  object
 11  pack_size        50000 non-null  object
 12  state            47581 non-null  object
 13  city_tier        47581 non-null  object
 14  occasion         47581 non-null  object
dtypes: float64(1), int64(1), object(13)
memory usage: 5.7+ MB

In [ ]:
merge_2[merge_2['state'].isnull()].sample(5)

,order_id,user_id,product_id,price,quantity,channel,date,time,category,claims,ingredient_tags,pack_size,state,city_tier,occasion
48909,ORD040279,U04827,P137,5.24,2,App,2025-11-24,23:07,Protein Shake,kosher,"oats, whey",Single,NaN,NaN,NaN
31570,ORD024751,U03744,P132,57.25,2,Gym Kiosk,2025-04-26,06:07,Proten Shake,plant-based,monk-fruit,4-Pack,NaN,NaN,NaN
12675,ORD037083,U03533,P008,9.32,3,Marketplace,2026-02-26,16:07,Protein bar,"diabetic-friendly, kosher","stevia, monk-fruit, almond-flour",Single,NaN,NaN,NaN
9908,ORD026893,U02209,P141,48.79,3,Retail,2025-08-20,15:07,Healthy Snack,"gluten-free, kosher, diabetic-friendly","almond-flour, collagen",4-Pack,NaN,NaN,NaN
39946,ORD026917,U01417,P101,15.52,1,Gym Kiosk,2025-07-22,16:07,Proten Shake,"keto-friendly, low-sugar, gluten-free, jain-fr...","pea-protein, almond-flour, monk-fruit",Single,NaN,NaN,NaN

In [ ]:
merge_2['state'].value_counts()

state
New York      9656
California    9526
Illinois      4809
Colorado      4748
Washington    4743
Texas         4734
Florida       4688
Georgia       4677
Name: count, dtype: int64

In [ ]:
merge_2['occasion'].value_counts()

occasion
late-night           12323
religious-fasting     6533
on-the-go             4913
festive               4901
daily snack           4831
gym                   4764
road-trip             4721
marathon-prep         4595
Name: count, dtype: int64

In [ ]:
#I WANT TO IMPUTE MISSING VALUES AT RANDOM IN COLUMNS SO THAT DATA DISTRIBUTION REMAIN SAME
states = ['New York', 'California', 'Illinois', 'Colorado',
          'Washington', 'Texas', 'Florida', 'Georgia']
merge_2.loc[merge_2['state'].isna(), 'state'] = np.random.choice(
    states,
    size=merge_2['state'].isna().sum()
)

In [ ]:
occasions = ['late-night', 'religious-fasting', 'on-the-go', 'festive',
          'daily snack', 'gym', 'road-trip', 'marathon-prep']
merge_2.loc[merge_2['occasion'].isna(), 'occasion'] = np.random.choice(
    occasions,
    size=merge_2['occasion'].isna().sum()
)
tie = ['Tier 1', 'Tier 2', 'Tier 3', 'Unknown']
merge_2.loc[merge_2['city_tier'].isna(), 'city_tier'] = np.random.choice(
    tie,
    size=merge_2['city_tier'].isna().sum()
)

In [ ]:
merge_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         50000 non-null  object
 1   user_id          50000 non-null  object
 2   product_id       50000 non-null  object
 3   price            50000 non-null  float64
 4   quantity         50000 non-null  int64
 5   channel          50000 non-null  object
 6   date             50000 non-null  object
 7   time             50000 non-null  object
 8   category         50000 non-null  object
 9   claims           50000 non-null  object
 10  ingredient_tags  50000 non-null  object
 11  pack_size        50000 non-null  object
 12  state            50000 non-null  object
 13  city_tier        50000 non-null  object
 14  occasion         50000 non-null  object
dtypes: float64(1), int64(1), object(13)
memory usage: 5.7+ MB

In [ ]:
#MERGE ALL OF THEM TO A SINGLE DATASET
df=pd.merge(merge_2, con, on='user_id', how='left')

In [ ]:
df.describe()

              price      quantity
count  50000.000000  50000.000000
mean      58.154038      4.099600
std      407.222003     20.383141
min        0.000000      1.000000
25%       10.657500      1.000000
50%       17.230000      2.000000
75%       36.870000      3.000000
max    18641.000000    299.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   order_id             50000 non-null  object
 1   user_id              50000 non-null  object
 2   product_id           50000 non-null  object
 3   price                50000 non-null  float64
 4   quantity             50000 non-null  int64
 5   channel              50000 non-null  object
 6   date                 50000 non-null  object
 7   time                 50000 non-null  object
 8   category             50000 non-null  object
 9   claims               50000 non-null  object
 10  ingredient_tags      50000 non-null  object
 11  pack_size            50000 non-null  object
 12  state                50000 non-null  object
 13  city_tier            50000 non-null  object
 14  occasion             50000 non-null  object
 15  persona              50000 non-null  object
 16  trend_affinity       50000 non-null  object
 17  age_group            50000 non-null  object
 18  gender_identity      50000 non-null  object
 19  income_bracket       50000 non-null  object
 20  dietary_restriction  20744 non-null  object
dtypes: float64(1), int64(1), object(19)
memory usage: 8.0+ MB

In [ ]:
df['dietary_restriction'].fillna('Nothing', inplace=True)

/tmp/ipykernel_19453/914513701.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['dietary_restriction'].fillna('Nothing', inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   order_id             50000 non-null  object
 1   user_id              50000 non-null  object
 2   product_id           50000 non-null  object
 3   price                50000 non-null  float64
 4   quantity             50000 non-null  int64
 5   channel              50000 non-null  object
 6   date                 50000 non-null  object
 7   time                 50000 non-null  object
 8   category             50000 non-null  object
 9   claims               50000 non-null  object
 10  ingredient_tags      50000 non-null  object
 11  pack_size            50000 non-null  object
 12  state                50000 non-null  object
 13  city_tier            50000 non-null  object
 14  occasion             50000 non-null  object
 15  persona              50000 non-null  object
 16  trend_affinity       50000 non-null  object
 17  age_group            50000 non-null  object
 18  gender_identity      50000 non-null  object
 19  income_bracket       50000 non-null  object
 20  dietary_restriction  50000 non-null  object
dtypes: float64(1), int64(1), object(19)
memory usage: 8.0+ MB

In [ ]:
df.to_csv('final_project.csv', index=False)
from google.colab import files
files.download('final_project.csv')

In [ ]:
df=pd.read_csv('/content/final_project.csv')

In [ ]:
df.sample(5)

,order_id,user_id,product_id,price,quantity,channel,date,time,category,claims,...,pack_size,state,city_tier,occasion,persona,trend_affinity,age_group,gender_identity,income_bracket,dietary_restriction
6812,ORD004786,U03772,P053,11.29,3,App,2025-07-06,13:07,Healthy Snack,vegan,...,Single,Florida,Unknown,daily snack,budget,gut-health,18-24,Man,Medium,Nothing
45720,ORD032405,U04392,P128,13.11,3,App,2025-05-01,05:07,Meal Replacement,"jain-friendly, low-sugar, diabetic-friendly",...,Single,New York,Tier 1,gym,casual,clean-label,35-44,Woman,Medium,Nothing
2767,ORD018807,U02255,P094,10.48,1,Website,2025-08-10,06:07,Protein Bar,gluten-free,...,Single,California,Tier 1,late-night,casual,plant-based,55+,Woman,High,Vegetarian
2532,ORD029527,U01053,P057,82.68,3,App,2026-02-17,08:07,Supplement,"keto-friendly, gluten-free, jain-friendly",...,12-Pack,New York,Tier 3,daily snack,premium,low-sugar,35-44,Man,Low,Nothing
15488,ORD016661,U03906,P129,14.51,1,App,2025-07-04,09:07,Electrolyte Drink,low-sugar,...,Single,California,Tier 2,marathon-prep,casual,protein,35-44,Woman,Low,Vegetarian

In [ ]:
df['total_price']=df['price']*df['quantity'].round(2)

In [ ]:
df.to_csv('final_project_new.csv', index=False)
from google.colab import files
files.download('final_project_new.csv')

In [ ]:
df['total_price']

0         21.33
1        131.20
2          7.18
3        146.19
4         24.00
          ...
49995     15.15
49996    131.79
49997     37.16
49998     65.22
49999     48.62
Name: total_price, Length: 50000, dtype: float64

In [ ]:
df['channel'].value_counts()

channel
Website        10060
App            10034
Gym Kiosk      10005
Marketplace     9961
Retail          9940
Name: count, dtype: int64

In [ ]:
df=pd.read_csv('/content/final_project_new.csv')

In [ ]:
df.describe()

              price      quantity   total_price
count  41379.000000  41379.000000  41379.000000
mean      58.568688      4.060876    188.719899
std      411.614513     20.025170   1443.994843
min        0.000000      1.000000      0.000000
25%       10.640000      1.000000     18.650000
50%       17.170000      2.000000     34.140000
75%       36.735000      3.000000     73.890000
max    18641.000000    299.000000  61080.000000

In [ ]:
df.columns

Index(['order_id', 'user_id', 'product_id', 'price', 'quantity', 'channel',
       'date', 'time', 'category', 'claims', 'ingredient_tags', 'pack_size',
       'state', 'city_tier', 'occasion', 'persona', 'trend_affinity',
       'age_group', 'gender_identity', 'income_bracket', 'dietary_restriction',
       'total_price'],
      dtype='object')

In [ ]:
df['category'].value_counts()

category
Meal Replacement     6697
Proten Shake         6365
Healthy Snack        5660
Protein Bar          5265
Electrolyte Drink    5036
Protein bar          4645
Supplement           4346
Protein Shake        3365
Name: count, dtype: int64

In [ ]:
df['category'] = df['category'].replace({
    'Protein bar': 'Protein Bar',
    'Proten Shake': 'Protein Shake'
})

In [ ]:
df.to_csv('final_project_new.csv', index=False)
from google.colab import files
files.download('final_project_new.csv')